apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongo
    project: robohsoop
    component: mongodb
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
    project: robohsoop
    component: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      project: robohsoop
      component: mongodb
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        project: robohsoop
        component: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: 000100000/amatkishore:22
          ports:
            - containerPort: 27017
